site_name: 轻墨星的笔记库
repo_name: inkstarchen/inkstarchen.cc
repo_url: https://github.com/inkstarchen/inkstarchen.cc
use_directory_urls: true
nav:
  - 首页: index.md
  - 思维与知识:
      - 总论: learning/index.md
      - 马克思主义: learning/marxism/marxism.md
      - 数据科学:
        - 数据结构: learning/data_science/data_structure.md
        - 基本算法: learning/data_science/algorithm.md
        - 近似算法: learning/data_science/approximate_algorithm.md
        - 排序: learning/data_science/sort.md
        - 搜索: learning/data_science/search.md
        - 并行: learning/data_science/parallel.md
      - 计算机系统: 
        - 总论: learning/computer-sys/computer-system.md
        - 计算机简史: learning/computer-sys/computer-history.md
        - 计算机系统三: learning/computer-sys/sys-3.md
        - 指标计算与思想: learning/computer-sys/mechanism.md
        - 电路基础: learning/computer-sys/foundation.md
        - 电路设计与Verilog使用: learning/computer-sys/verilog.md
        - ELF文件: learning/computer-sys/ELF.md
        - 操作系统结构: learning/computer-sys/structure.md
        - 进程: learning/computer-sys/process.md
        - 线程: learning/computer-sys/thread.md
        - 计算机如何运作: learning/computer-sys/how-computer-work.md
      - 计算机网络: 
        - 网络: learning/computer-network/network.md
        - 杂七杂八: learning/computer-network/other.md
        - 服务器软件: learning/computer-network/serversoftware.md
        - Nginx介绍: learning/computer-network/learn-Nginx.md
      - 计算机视觉: 
        - 引子: learning/computer-vision/introduction.md
        - 图像滤波: learning/computer-vision/image-filter.md
      - 计算机图形学:
        - 总论: learning/computer-graphics/index.md
        - 变换: learning/computer-graphics/transform.md
      - 信息安全:
        - 加密算法: learning/information_security/encryption.md
      - 量子计算:
        - 总论: learning/quantum/quantum.md
      - 脑机接口:
        - 总论: learning/brain-interface/index.md
        - 大脑模拟: learning/brain-interface/brain.md
      - 软件工程: 
        - 前端: learning/software_construction/front-end.md
        - 软件设计模式: learning/software_construction/design.md
      - 机器人学: learning/robotics.md
      - 人工智能: 
        - 引论: learning/AI/ai-introduction.md
        - 机器学习: learning/AI/machine-learning.md
        - 贝叶斯分类器: learning/AI/bayesian.md
        - 监督学习: learning/AI/supervised_learning.md
        - 深度学习: learning/AI/deep-learning.md
        - 强化学习: learning/AI/reinforcement-learning.md
        - 决策与博弈算法: learning/AI/game-algorithm.md
        - 多智能体强化学习: learning/AI/multi-agent-reinforcement-learning.md
      - 技术原则: learning/tech_prin.md
      - 历史经验: learning/history.md
      - 博弈论基础: learning/game-theory.md
      - 数据库系统:
        - 理论知识:
          - 总览: learning/database/theory.md
          - 物理存储: learning/database/physical-level.md
          - 关系模型: learning/database/relation_schema.md
          - 数据库设计: learning/database/base_design.md
          - 索引: learning/database/indexes.md
          - 查询开销估计与优化: learning/database/query.md
          - 事务:  learning/database/transaction.md
          - 恢复管理器: learning/database/recoverymanager.md
        - Mysql使用: learning/database/mysql.md
        - Mysql知识: learning/database/mysql-know.md
      - 通信原理: 
        - 相关数学知识: learning/communication/communication-theory.md
        - 信号:  learning/communication/signal.md
      - 物理学: learning/physics.md
      - 社会心理学: learning/social-psychology.md
      - 设计: learning/design.md
      - 毛泽东思想与中国特色社会主义理论体系概论: learning/maogai.md
      - 文件类型: 
        - GLTF文件: learning/files/gltf.md
        - SO文件: learning/files/so.md
  - 数学工具:
    - 总论: maths/index.md
    - 数学基础:
        - 欧几里得空间: maths/bases/euclidean-space.md
        - 范数: maths/bases/norm.md
        - 数学工具: maths/bases/math-tools.md
    - 数理逻辑: 
        - 命题逻辑与谓词逻辑: maths/mathematical_logic/statement_predicate_logic.md
        - 推理: maths/mathematical_logic/infer.md
    - 优化基础理论:
      - Lec1: maths/optimization/Lec1.md
      - 拉格朗日乘子法: maths/optimization/lagrange.md
    - 理论计算机科学导引:
      - 编码: maths/Theorical/encoding.md
      - 电路与函数: maths/Theorical/function.md
    - 数学分析:
      - 函数: maths/calculate/function.md
      - 函数极限: maths/calculate/functionlimit.md
      - 函数性质: maths/calculate/Pfunction.md
      - 微积分定理: maths/calculate/cal2.md
      - 无界函数反常积分: maths/calculate/cal1.md
      - 其它定理: maths/calculate/otherTheorem.md
      - 数列: maths/calculate/number.md
      - 实数系完备性定理: maths/calculate/Theorem1.md
    - 线性代数: 
      - 总论: maths/linear/index.md 
      - 抽象部分: maths/linear/abstract.md
      - 矩阵: maths/linear/matrix.md
      - 矩阵运算: maths/linear/calmatrix.md
      - 特殊矩阵分类: maths/linear/specialMatrix.md
      - 特征值与特征向量: maths/linear/characteristic.md
      - 线性代数证明: maths/linear/proof.md
      - 线性空间: maths/linear/space.md
      - 线性映射: maths/linear/mapping.md
      - 向量: maths/linear/vector.md
      - 行列式: maths/linear/matrix2.md
    - 概率论: 
      - 概率论知识: maths/probability/probability.md
      - 分布函数表: maths/probability/distribution.md
  - 知识论:
      - 知识的传递: 
        - 写作: knowledge/pass/writing.md
        - 报告写作: knowledge/pass/report.md
        - 论文写作: knowledge/pass/paper.md
        - 听的艺术: knowledge/pass/listen.md
        - 内容呈现: knowledge/pass/ppt.md
      - 学习与教育: knowledge/education.md
      - 知识论: knowledge/know.md
      - 研究之路: knowledge/research.md
  - 认知: 
    - 软件调研: know/Software.md
    - 名词解释: know/noun.md
  - 人与社会: 
    - 社会幻象: human-society/social-illusions.md
    -  政府: human-society/government.md
    - 工作生活: human-society/society.md
    - 迈向社会: human-society/school-society.md
    - 注意力: human-society/attention.md
    - 原则与策略: human-society/strategy.md
  - 人之体验:
    - 生活: Experience/index.md
    - 杂言: Experience/mix.md
    - 摄影: Experience/photo/photograph.md
    - 前人之言:
      - 爱因斯坦: Experience/quotes/Einstein.md
      - 乔布斯: Experience/quotes/SteveJobs.md
    - 感受:
      - 情绪: Experience/Feeling/emotion.md
      - 禅: Experience/Feeling/zen.md
    - 书籍:
      - 大问题:简明哲学导论: Experience/Books/big_questions.md
      - 雕刻时光: Experience/Books/curve_time.md
      - 毛选: Experience/Books/mao-xuan.md
    - 旧文:
      - 中心的骗局: Experience/OldWords/lie-of-center.md
      - 坚韧不拔的磐石: Experience/OldWords/tough-stone.md
      - 初中片段:  Experience/OldWords/old-words.md
      - 新: Experience/OldWords/newlife.md
    - 音乐:
      - 工作流音乐: Experience/music/workflow.md
    -  文学:
        - 废名: Experience/literature/fei-ming.md
        - 鲁迅: Experience/literature/lu-xun.md
        - 穆时英: Experience/literature/mu-shi-ying.md
        - 施蛰存: Experience/literature/shi-zhe-cun.md
        - 文学研究会: Experience/literature/wen-xue-hui-yan.md
        - 萧红: Experience/literature/xiao-hong.md
        - 郁达夫: Experience/literature/yu-da-fu.md
        - 赵树理: Experience/literature/zhao-shu-li.md
    - 茶:
        - 茶文化: Experience/tea/tea-culture.md
        - 茶健康: Experience/tea/tea-health.md
        - 茶科技: Experience/tea/tea-science.md
        - 茶产业: Experience/tea/tea-industry.md
        - 茶文化与茶健康复习提纲: Experience/tea/tea-culture-tea-health-review.md
  - 技术知识:
      - SSH:
        - 什么是SSH: tech-know/SSH/SSH.md
      - C++:
        - 基本语法: tech-know/Cpp/Cpp-basic.md
        - 编写规范: tech-know/Cpp/Cpp-rule.md
        - 关键字: tech-know/Cpp/Cpp-keyword.md
        - Vector 容器的使用: tech-know/Cpp/Cpp-vector.md
        - 类的使用: tech-know/Cpp/Cpp-class.md
        - G++ 编译事项: tech-know/Cpp/g++.md
        - Allocator: tech-know/Cpp/Cpp-allocator.md
        - 异常: tech-know/Cpp/Cpp-exception.md
        - 迭代器: tech-know/Cpp/Cpp-iterators.md
        - 异步执行: tech-know/Cpp/Cpp-async.md
      - VNC:
        - BUG: tech-know/VNC/VNC-bug.md
      - 鸿蒙应用开发经验:
        - 基础知识: tech-know/Harmony/HOS-basic.md
        - 框架: tech-know/Harmony/HOS-framework.md
      - Python: tech-know/Python.md
      - Kotlin: 
        - 数据类型: tech-know/Kotlin-datatype.md
        - 错误汇总: tech-know/Kotlin-error.md
      - Android Studio: tech-know/As.md
      - Learn Git: 
        - 基础知识: tech-know/LearnGit.md
        - 错误汇总: tech-know/git-error.md
      - Learn Latex: tech-know/LearnLatex.md
      - Learn Markdown: tech-know/LearnMarkdown.md
      - 文件类型: tech-know/file-type.md
      - Learn Makefile: tech-know/Makefile.md
  - 网站搭建:
    - mkdocs配置:
      - pydownx: Website/mkdocs-pydownx.md
      - Admonitions: Website/mkdocs-admonition.md
      - 技巧: Website/mkdocs-tips.md
      - 基础设置: Website/mkdocs-setting.md
 

markdown_extensions:
  - md_in_html  
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.mark
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

theme: 
  name: material
  palette:
    primary: blue
  features:
    - search.suggest
    - content.code.annotate
    - content.code.select #付费功能
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.code.annotate
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
extra_css:
  - css/counter.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  