site_name: MkLorum
site_url: index.md
repo_url: https://github.com/inkstarchen/inkstarchen.cc
edit_uri: tree/main/docs
nav:
  - Home: index.md
  - About: about.md
  - 社会心理学: social.md
theme: 
  name: material
  features:
    - search.suggest
plugins:
  - search
  
