site_name: 轻墨星的笔记库
repo_name: inkstarchen/inkstarchen.cc
repo_url: https://github.com/inkstarchen/inkstarchen.cc
use_directory_urls: true
nav:
  - 阅读指引: index.md
  - 信念网: my-blief.md
  - 工作空间:
      - 总论: workspace/index.md
      - 优化基础理论:
        - Lec1: workspace/optimization/Lec1.md
        - 拉格朗日乘子法: workspace/optimization/lagrange.md
        - 新记录: workspace/optimization/Theorem.md
        - 作业: workspace/optimization/hw.md
      - 理论计算机科学导引:
        - 编码: workspace/Theorical/encoding.md
        - 定义计算: workspace/Theorical/computation.md
        - 语法糖: workspace/Theorical/sugar.md
        - 代码与数据: workspace/Theorical/code_data.md
        - 无限域函数、自动机和正则表达式: workspace/Theorical/regular.md
        - 未定义: workspace/Theorical/un.md
        - 参考书籍: workspace/Theorical/reference.md
      - 工具: 
        - 卡尔曼滤波: workspace/tools/Kalman-filter.md
        - 拉格朗日乘子法: workspace/tools/lagrange.md
        - 傅里叶变换: workspace/tools/fourier.md
      - 计算机系统: 
        - 总论: workspace/computer-sys/computer-system.md
        - 计算机如何运作: workspace/computer-sys/how-computer-work.md
        - 计算机简史: workspace/computer-sys/computer-history.md
        - 缓存机制: workspace/computer-sys/cache.md
        - 指标计算与思想: workspace/computer-sys/mechanism.md
        - 分页机制: workspace/computer-sys/paging.md
        - 流水线与乱序执行: workspace/computer-sys/pipeline.md
        - 文件系统: workspace/computer-sys/filesystem.md
        - 进程与线程: workspace/computer-sys/process-thread.md
        - 并行计算: workspace/computer-sys/parallel.md
        - IO: workspace/computer-sys/IO.md
      - 计算机视觉: 
        - 补充内容: workspace/computer-vision/appendix.md
      - 计算机图形学:
        - 总论: workspace/computer-graphics/index.md
        - OpenGL使用: workspace/computer-graphics/opengl.md
        - 变换: workspace/computer-graphics/transform.md
        - 透明物体绘制: workspace/computer-graphics/transparency.md
        - 光照: workspace/computer-graphics/lighting.md
        - 多实例: workspace/computer-graphics/instance.md
        - 后处理: workspace/computer-graphics/post-processing.md
        - 物理: workspace/computer-graphics/physics.md
        - 性能优化: workspace/computer-graphics/performance.md
      - 量子计算:
        - 总论: workspace/quantum/quantum.md
        - 量子比特: workspace/quantum/qubit.md
        - 量子门: workspace/quantum/gate.md
        - 量子计算: workspace/quantum/quantum-computing.md
        - 量子实验: workspace/quantum/quantum-experiment.md
        - 量子算法: workspace/quantum/quantum-algorithm.md
        - 量子测量: workspace/quantum/quantum-measurement.md
        - 量子纠错: workspace/quantum/quantum-error-correction.md
        - 术语: workspace/quantum/terminology.md
      - 人工智能: 
        - 机器学习: workspace/AI/machine-learning.md
        - 贝叶斯分类器: workspace/AI/bayesian.md
      - 线性代数: workspace/linear.md 
      - 概率论知识: workspace/probability.md
      - 技术累计:
        - 索引结构: workspace/database/indexes.md
        - 恢复管理器: workspace/database/recoverymanager.md
        - 存储结构: workspace/database/physical-level.md
      - 文件类型: 
        - GLTF文件: workspace/files/gltf.md
        - SO文件: workspace/files/so.md
        - ELF文件: workspace/files/ELF.md
  - 启发材料: 
    - 书籍:
      - 大问题:简明哲学导论: inspiration/Books/big_questions.md
      - 雕刻时光: inspiration/Books/curve_time.md
      - 社会幻象: inspiration/Books/social-illusions.md
    - 博弈论: inspiration/game-theory.md
    - 社会心理学: inspiration/social-psychology.md
    - 旧文归档: inspiration/old-words.md
    - 音乐:
      - 工作流音乐: inspiration/music/workflow.md
  - 技术知识:
      - C++:
        - 基本语法: tech-know/Cpp/Cpp-basic.md
        - 编写规范: tech-know/Cpp/Cpp-rule.md
        - 关键字: tech-know/Cpp/Cpp-keyword.md
        - Vector 容器的使用: tech-know/Cpp/Cpp-vector.md
        - 类的使用: tech-know/Cpp/Cpp-class.md
        - G++ 编译事项: tech-know/Cpp/g++.md
        - Allocator: tech-know/Cpp/Cpp-allocator.md
        - 异常: tech-know/Cpp/Cpp-exception.md
        - 迭代器: tech-know/Cpp/Cpp-iterators.md
        - 异步执行: tech-know/Cpp/Cpp-async.md
      - VNC:
        - BUG: tech-know/VNC/VNC-bug.md
      - 鸿蒙应用开发经验:
        - 基础知识: tech-know/Harmony/HOS-basic.md
        - 框架: tech-know/Harmony/HOS-framework.md
      - Learn Makefile: tech-know/Makefile.md
      - 网站搭建:
        - mkdocs配置: tech-know/mkdocs.md
 

markdown_extensions:
  - md_in_html  
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.mark
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

theme: 
  name: material
  palette:
    primary: blue
  features:
    - search.suggest
    - content.code.annotate
    - content.code.select #付费功能
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.code.annotate
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
extra_css:
  - css/counter.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  