site_name: 轻墨星的笔记库
repo_name: inkstarchen/inkstarchen.cc
repo_url: https://github.com/inkstarchen/inkstarchen.cc
use_directory_urls: true
nav:
  - 欢迎: index.md
  - 学习:
      - 动手学深度学习: 
          - 预备知识:
              - 概率: learning/deeplearning/2/2.6.md
          - 线性神经网络:
              - 线性回归: learning/deeplearning/3/3.1.md
  - 课程笔记:
      - 微信小程序: class/classnote-wx.md
      - 报告写作: class/classnote-write.md
      - 中国近现代史纲: class/history.md
      - 博弈论基础: class/game-theory.md
      - 计算机系统: 
        - 理论知识: class/computer-system.md
        - Verilog使用: class/verilog.md
        - reg和时序电路: class/reg.md
        - 阻塞赋值和非阻塞赋值: class/sys-1.md
  - 工作笔记:
      - Learn Git: 
        - 基础知识: LearnGit.md
        - 错误汇总: git-error.md
      - Learn Latex: LearnLatex.md
      - Learn Markdown: LearnMarkdown.md
      - Learn Internet: 
        - 杂七杂八: LearnInternet.md
        - 服务器软件: learn-softwareweb.md
        - Nginx介绍: learn-Nginx.md
  - 编程语言学习:
      - C++:
        - 基本语法: Cpp-basic.md
      - Kotlin: 
        - 数据类型: Kotlin-datatype.md
        - 错误汇总: Kotlin-error.md
  - 软件使用:
      - Android Studio: As.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

theme: 
  name: material
  palette:
    primary: blue
  features:
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.code.annotate
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  